<a href="https://colab.research.google.com/github/sak-shi-collab/8_SAKSHI_D2/blob/main/api_to_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [3]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [5]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,56.3199,8.700,29936
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,39.5995,8.687,22615
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,21.1650,8.572,13697
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.7852,8.567,17219
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,16.5541,8.600,9821

In [6]:
df= pd.DataFrame()

In [7]:
df

Empty DataFrame
Columns: []
Index: []

In [12]:
all_dfs = []
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    all_dfs.append(temp_df)

df = pd.concat(all_dfs, ignore_index=True)

In [13]:
df.shape

(8560, 7)

In [11]:
temp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20 non-null     int64
 1   title         20 non-null     object
 2   overview      20 non-null     object
 3   release_date  20 non-null     object
 4   popularity    20 non-null     float64
 5   vote_average  20 non-null     float64
 6   vote_count    20 non-null     int64
dtypes: float64(2), int64(2), object(3)
memory usage: 1.2+ KB

In [14]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,56.3199,8.700,29936
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,39.5995,8.687,22615
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,21.1650,8.572,13697
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.7852,8.567,17219
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,16.5541,8.600,9821
...,...,...,...,...,...,...,...
8555,123109,No One Lives,A gang of ruthless highway killers kidnap a we...,2013-03-09,1.7470,5.988,685
8556,930600,The Deliverance,"Ebony Jackson, a struggling single mother figh...",2024-08-16,2.7631,5.987,533
8557,921636,The Out-Laws,A straight-laced bank manager is about to marr...,2023-07-07,3.3070,6.000,785
8558,800345,Carter,"Carter, who awakens two months into a deadly p...",2022-08-05,3.3709,5.987,416
8559,672582,The Deep House,"While diving in a remote French lake, a couple...",2021-06-30,2.1815,6.000,1086

In [15]:
df.shape

(8560, 7)